[package]
name = "zuulgraph"
version = "0.1.0"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.3"
rand = "0.7.2"
regex = "1.3.1"